Update angles version and shasum
ros-melodic-arch/ros-melodic-angles pull request #2
Opened 2020-04-24 12:11 UTC by ruffson

Bumbed up to 1.9.13.

This is required if one e.g. has to use the `ros_controllers` package as they rely on the new `shortest_angular_distance_with_large_limits` function.

2020-04-24 18:49 UTC, jwhendy commented
I can build this, so no problems there. Would you kindly update `.SRCINFO` as well, then re-push?

```
makepkg --printsrcinfo > .SRCINFO
```

2020-04-25 05:55 UTC, ruffson commented
> I can build this, so no problems there. Would you kindly update `.SRCINFO` as well, then re-push?
> 
> ```
> makepkg --printsrcinfo > .SRCINFO
> ```

Sorry, new to Arch. I amended my commit.

2020-04-25 16:25 UTC, acxz requested changes

2020-04-25 16:25 UTC, acxz commented on PKGBUILD
>  pkgrel=2
can u bump the pkgrel down to 1 since we are updating the pkgver.

2020-04-25 20:09 UTC, acxz approved these changes

2020-04-25 20:09 UTC, acxz commented
Looks good LGTM thx for your contribution!

2020-04-25 20:09 UTC, merged

2020-04-26 16:26 UTC, jwhendy commented
@ruffson thanks for enduring the tweaks, and we appreciate the contribution!